import re
from datetime import datetime,timezone
from uuid import uuid4
from .core.config import settings
def now():return datetime.now(timezone.utc)
def audit(db,resource_id,action,actor_id,metadata=None):db.audit_logs.insert_one({'resource_id':resource_id,'action':action,'actor_id':actor_id,'metadata':metadata or {},'created_at':now()})
def field(value,confidence):return {'value':value,'confidence':confidence,'page':1,'bbox':None,'model_version':'baseline-rules-v1'}
def process_document(db,document_id,actor_id):
 doc=db.documents.find_one({'document_id':document_id});
 if not doc: raise ValueError(f'Document {document_id} was not found')
 nums=re.findall(r'\d+',doc['original_name']);name=re.sub(r'[^a-zA-Z0-9]+',' ',doc['original_name']).strip();fields={'owner':field('Unverified owner',.62),'survey_no':field(nums[0] if nums else '',.74),'khasra_no':field('/'.join(nums[:2]),.78),'khata_no':field(nums[-1] if nums else '',.71),'area':field('',.55),'village':field('Unverified village',.65),'tehsil':field('',.60),'district':field('',.60),'classification':field('',.58),'mutation_no':field('',.55),'registration_no':field('',.55),'source_title':field(name,.98)};confidence=sum(x['confidence'] for x in fields.values())/len(fields);reasons=['low_confidence_'+k for k in ('owner','area','village','district') if fields[k]['confidence']<settings.model_confidence_threshold];rid='LR-'+uuid4().hex[:12].upper();status='needs_review' if reasons else 'verified';record={'record_id':rid,'document_id':document_id,'fields':fields,'owner':fields['owner']['value'],'survey_no':fields['survey_no']['value'],'khasra_no':fields['khasra_no']['value'],'khata_no':fields['khata_no']['value'],'village':fields['village']['value'],'tehsil':fields['tehsil']['value'],'district':fields['district']['value'],'confidence':confidence,'status':status,'created_at':now(),'updated_at':now()};db.land_records.insert_one(record);db.ocr_results.insert_one({'document_id':document_id,'page':1,'text':'Baseline extraction. Configure OCR worker for production.','fields':fields,'created_at':now()});db.validations.insert_one({'record_id':rid,'reason_codes':reasons,'confidence':confidence,'created_at':now()});
 if reasons:db.verification_tasks.insert_one({'task_id':'VT-'+uuid4().hex[:10].upper(),'record_id':rid,'document_id':document_id,'status':'pending','reason_codes':reasons,'confidence':confidence,'created_at':now()})
 db.documents.update_one({'_id':document_id},{'$set':{'status':'needs_review' if reasons else 'complete','processed_at':now()}});audit(db,document_id,'document_processed',actor_id,{'record_id':rid,'confidence':confidence});return record
